"""Derive severity-engine size thresholds from the TRAIN split box sizes.

For every class, box area (% of image) is measured on the train labels only.
Thresholds written to inference/severity_rules.yaml:
  major_area    = class median (p50)  -> box bigger than a typical defect of that class
  critical_area = class p90           -> box bigger than 90% of that class's defects

This is a data-relative engineering assumption, NOT an industrial QC standard.
Real limits must come from the product's QC specification (ideally in mm^2).

Usage (project root):
  .\.venv\Scripts\python.exe scripts\calibrate_severity.py
"""
from pathlib import Path

import numpy as np
import yaml

ROOT = Path(__file__).resolve().parents[1]
DATA_YAML = ROOT / "training" / "neu_det.yaml"
OUT = ROOT / "inference" / "severity_rules.yaml"


def main():
    cfg = yaml.safe_load(DATA_YAML.read_text(encoding="utf-8"))
    names = cfg["names"]
    label_dir = ROOT / "dataset" / "processed" / "neu_det" / "labels" / "train"
    files = sorted(label_dir.glob("*.txt"))
    if not files:
        raise SystemExit(f"No label files in {label_dir}. Run scripts/prepare_neu_det.py first.")

    areas = {i: [] for i in names}
    for f in files:
        for line in f.read_text().split("\n"):
            parts = line.split()
            if len(parts) != 5:
                continue
            cls, w, h = int(parts[0]), float(parts[3]), float(parts[4])
            areas[cls].append(w * h * 100.0)  # YOLO w,h are normalised -> % of image

    classes = {}
    print(f"{'class':<16}{'boxes':>6}{'p50 %':>8}{'p90 %':>8}")
    for i, name in names.items():
        a = np.array(areas[i])
        p50, p90 = float(np.percentile(a, 50)), float(np.percentile(a, 90))
        print(f"{name:<16}{len(a):>6}{p50:>8.1f}{p90:>8.1f}")
        classes[name] = {
            "min_severity": "minor",
            "major_area": round(p50, 2),
            "critical_area": round(p90, 2),
            "train_boxes": len(a),
        }

    rules = {
        "source": f"scripts/calibrate_severity.py on {len(files)} train label files "
                  "(NEU-DET, seed 42). Areas in % of image. Data-relative assumption, "
                  "not an industrial standard.",
        "confidence": {"min": 0.25, "review": 0.50},
        "count_escalation": 3,
        "decisions": {"none": "PASS", "minor": "PASS_WITH_NOTE",
                      "major": "REWORK", "critical": "REJECT"},
        "classes": classes,
    }
    header = ("# Severity rules for inference/severity.py.\n"
              "# classes.*.major_area / critical_area are GENERATED by scripts/calibrate_severity.py.\n"
              "# confidence, count_escalation, decisions and min_severity are hand-set starting\n"
              "# values (assumptions) - edit them here and re-run tests/test_severity.py.\n")
    if OUT.exists():  # keep hand-edited settings, refresh only the measured thresholds
        old = yaml.safe_load(OUT.read_text(encoding="utf-8"))
        for key in ("confidence", "count_escalation", "decisions"):
            rules[key] = old.get(key, rules[key])
        for name, c in classes.items():
            c["min_severity"] = old.get("classes", {}).get(name, {}).get("min_severity", "minor")
    OUT.write_text(header + yaml.safe_dump(rules, sort_keys=False), encoding="utf-8")
    print(f"\nWrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
